all: main.c qb_object_foo.c qb_object_bar.c ../utils/logger/qb_logger.c
	gcc -std=c99 -Wall -Wextra -Wpedantic -Werror -o method main.c qb_object_foo.c qb_object_bar.c ../utils/logger/qb_logger.c

clean:



